# Book settings
title: <%- JSON.stringify(name) %>
author: <%- JSON.stringify(displayName) %>
description: <%- JSON.stringify(description) %>
logo: logo.png

execute:
  execute_notebooks         : "cache"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

latex:
  latex_documents:
    targetname: book.tex